using System.Collections.Generic;

namespace Flyknit.Client.Services;

/// <summary>原生界面（托盘菜单、悬浮球提示、注册窗口、划词翻译浮窗）的三语文案。Web 界面的文案在 client/web/src/i18n。</summary>
public static class NativeStrings
{
    private static readonly Dictionary<string, Dictionary<string, string>> Table = new()
    {
        ["zh-CN"] = new()
        {
            ["tray.open"] = "打开 FlyknitBuddy",
            ["tray.newChat"] = "新建对话",
            ["tray.ball"] = "显示悬浮球",
            ["tray.exit"] = "退出",
            ["ball.tip"] = "有什么可以帮你？",
            ["ball.waiting"] = "有操作等待你确认",
            ["setup.title"] = "连接 Flyknit 服务器",
            ["setup.intro"] = "首次使用需要连接公司的 Flyknit 服务器。服务器地址和注册密钥请向 IT 部门获取。",
            ["setup.server"] = "服务器地址",
            ["setup.key"] = "注册密钥",
            ["setup.connect"] = "连接",
            ["setup.connecting"] = "正在连接…",
            ["setup.failed"] = "连接失败：{0}",
            ["login.title"] = "登录 FlyknitBuddy",
            ["login.intro"] = "用这台电脑的 Windows 账号登录，登录后就能开始使用。",
            ["login.domainHint"] = "公司域账号，开机时已经验证过身份，直接点登录即可",
            ["login.localHint"] = "这台电脑的本机账号，请输入开机时用的 Windows 密码",
            ["login.password"] = "Windows 密码（没有设置密码就留空）",
            ["login.server"] = "服务器：{0}",
            ["login.button"] = "登录",
            ["login.useManual"] = "手动连接服务器",
            ["login.useLogin"] = "返回用 Windows 账号登录",
            ["login.wrongPassword"] = "密码不对。请输入这台电脑开机时用的 Windows 密码（不是 PIN 码）。",
            ["login.verifyFailed"] = "Windows 没能验证这个账号：{0}",
            ["error.webview"] = "缺少 Microsoft Edge WebView2 运行时，请联系 IT 安装后重试。",
            ["confirm.notify"] = "FlyknitBuddy 需要你确认一个操作",
            ["toast.appName"] = "FlyknitBuddy",
            ["toast.confirmTitle"] = "FlyknitBuddy 需要你确认一个操作",
            ["toast.allow"] = "允许",
            ["toast.reject"] = "拒绝",
            ["toast.view"] = "查看",
            ["toast.done"] = "任务已完成",
            ["toast.paused"] = "任务已暂停",
            ["toast.failed"] = "任务出错了",
            ["loading.title"] = "正在启动 FlyknitBuddy…",
            ["loading.subtitle"] = "准备就绪后将自动打开工作区。",
            ["mcp.oauthDone"] = "登录完成，可以关掉这个页面回到 FlyknitBuddy，连接结果以 FlyknitBuddy 里显示的为准。",
            ["mcp.oauthFailed"] = "登录没有完成，请回到 FlyknitBuddy 重新连接。",
            ["sel.title"] = "划词翻译",
            ["sel.target"] = "译成哪种语言",
            ["sel.pin"] = "钉住（点别处不关）",
            ["sel.close"] = "关闭（Esc）",
            ["sel.sourceHint"] = "可以改原文，按 Enter 重新翻译",
            ["sel.copy"] = "复制",
            ["sel.copied"] = "已复制",
            ["sel.continue"] = "在主窗口继续",
            ["sel.empty"] = "没读到选中的文字。在这里输入或粘贴，按 Enter 翻译。",
            ["sel.working"] = "正在翻译…",
            ["sel.noResult"] = "没有得到译文，换个语言再试一次。",
            ["sel.truncated"] = "选中的太长，只翻译了前 {0} 个字。整份文件请用翻译模式。",
            ["sel.error.auth"] = "服务器拒绝了请求，可能是本机授权过期了，请联系 IT。",
            ["sel.error.busy"] = "模型服务繁忙或已到今天的用量上限，稍后再试。",
            ["sel.error.network"] = "连不上服务器，检查一下网络。",
            ["sel.error.failed"] = "翻译失败：{0}",
            ["lang.zh-CN"] = "中文",
            ["lang.vi"] = "越南语",
            ["lang.en"] = "英语",
            ["lang.km"] = "柬埔寨语",
            ["lang.th"] = "泰语",
            ["lang.id"] = "印尼语",
            ["lang.ja"] = "日语",
            ["lang.ko"] = "韩语",
        },
        ["vi-VN"] = new()
        {
            ["tray.open"] = "Mở FlyknitBuddy",
            ["tray.newChat"] = "Trò chuyện mới",
            ["tray.ball"] = "Hiện nút nổi",
            ["tray.exit"] = "Thoát",
            ["ball.tip"] = "Tôi có thể giúp gì cho bạn?",
            ["ball.waiting"] = "Có thao tác đang chờ bạn xác nhận",
            ["setup.title"] = "Kết nối máy chủ Flyknit",
            ["setup.intro"] = "Lần đầu sử dụng cần kết nối máy chủ Flyknit của công ty. Vui lòng hỏi bộ phận IT địa chỉ máy chủ và mã đăng ký.",
            ["setup.server"] = "Địa chỉ máy chủ",
            ["setup.key"] = "Mã đăng ký",
            ["setup.connect"] = "Kết nối",
            ["setup.connecting"] = "Đang kết nối…",
            ["setup.failed"] = "Kết nối thất bại: {0}",
            ["login.title"] = "Đăng nhập FlyknitBuddy",
            ["login.intro"] = "Đăng nhập bằng tài khoản Windows của máy này để bắt đầu sử dụng.",
            ["login.domainHint"] = "Tài khoản miền công ty, đã được xác thực khi khởi động máy, chỉ cần bấm Đăng nhập",
            ["login.localHint"] = "Tài khoản cục bộ của máy này, hãy nhập mật khẩu Windows dùng khi mở máy",
            ["login.password"] = "Mật khẩu Windows (để trống nếu không đặt mật khẩu)",
            ["login.server"] = "Máy chủ: {0}",
            ["login.button"] = "Đăng nhập",
            ["login.useManual"] = "Kết nối máy chủ thủ công",
            ["login.useLogin"] = "Quay lại đăng nhập bằng tài khoản Windows",
            ["login.wrongPassword"] = "Sai mật khẩu. Hãy nhập mật khẩu Windows dùng khi mở máy (không phải mã PIN).",
            ["login.verifyFailed"] = "Windows không xác thực được tài khoản này: {0}",
            ["error.webview"] = "Thiếu Microsoft Edge WebView2 Runtime, vui lòng liên hệ IT để cài đặt.",
            ["confirm.notify"] = "FlyknitBuddy cần bạn xác nhận một thao tác",
            ["toast.appName"] = "FlyknitBuddy",
            ["toast.confirmTitle"] = "FlyknitBuddy cần bạn xác nhận một thao tác",
            ["toast.allow"] = "Cho phép",
            ["toast.reject"] = "Từ chối",
            ["toast.view"] = "Xem",
            ["toast.done"] = "Nhiệm vụ đã hoàn thành",
            ["toast.paused"] = "Nhiệm vụ đã tạm dừng",
            ["toast.failed"] = "Nhiệm vụ gặp lỗi",
            ["loading.title"] = "Đang khởi động FlyknitBuddy…",
            ["loading.subtitle"] = "Không gian làm việc sẽ tự mở khi sẵn sàng.",
            ["mcp.oauthDone"] = "Đã đăng nhập xong, bạn có thể đóng trang này và quay lại FlyknitBuddy để xem kết quả kết nối.",
            ["mcp.oauthFailed"] = "Đăng nhập chưa hoàn tất, vui lòng quay lại FlyknitBuddy và kết nối lại.",
            ["sel.title"] = "Dịch nhanh",
            ["sel.target"] = "Dịch sang ngôn ngữ nào",
            ["sel.pin"] = "Ghim (bấm chỗ khác không đóng)",
            ["sel.close"] = "Đóng (Esc)",
            ["sel.sourceHint"] = "Có thể sửa văn bản gốc, nhấn Enter để dịch lại",
            ["sel.copy"] = "Sao chép",
            ["sel.copied"] = "Đã sao chép",
            ["sel.continue"] = "Tiếp tục trong cửa sổ chính",
            ["sel.empty"] = "Không đọc được văn bản đã chọn. Nhập hoặc dán vào đây rồi nhấn Enter để dịch.",
            ["sel.working"] = "Đang dịch…",
            ["sel.noResult"] = "Không nhận được bản dịch, hãy thử ngôn ngữ khác.",
            ["sel.truncated"] = "Đoạn chọn quá dài, chỉ dịch {0} ký tự đầu. Dịch cả tệp hãy dùng chế độ Dịch.",
            ["sel.error.auth"] = "Máy chủ từ chối yêu cầu, có thể quyền của máy này đã hết hạn. Vui lòng liên hệ IT.",
            ["sel.error.busy"] = "Dịch vụ mô hình đang bận hoặc đã hết hạn mức hôm nay, vui lòng thử lại sau.",
            ["sel.error.network"] = "Không kết nối được máy chủ, hãy kiểm tra mạng.",
            ["sel.error.failed"] = "Dịch thất bại: {0}",
            ["lang.zh-CN"] = "Tiếng Trung",
            ["lang.vi"] = "Tiếng Việt",
            ["lang.en"] = "Tiếng Anh",
            ["lang.km"] = "Tiếng Khmer",
            ["lang.th"] = "Tiếng Thái",
            ["lang.id"] = "Tiếng Indonesia",
            ["lang.ja"] = "Tiếng Nhật",
            ["lang.ko"] = "Tiếng Hàn",
        },
        ["en-US"] = new()
        {
            ["tray.open"] = "Open FlyknitBuddy",
            ["tray.newChat"] = "New chat",
            ["tray.ball"] = "Show floating button",
            ["tray.exit"] = "Exit",
            ["ball.tip"] = "How can I help?",
            ["ball.waiting"] = "An action is waiting for your approval",
            ["setup.title"] = "Connect to the Flyknit server",
            ["setup.intro"] = "Connect to your company's Flyknit server to get started. Ask IT for the server address and enrollment key.",
            ["setup.server"] = "Server address",
            ["setup.key"] = "Enrollment key",
            ["setup.connect"] = "Connect",
            ["setup.connecting"] = "Connecting…",
            ["setup.failed"] = "Couldn't connect: {0}",
            ["login.title"] = "Sign in to FlyknitBuddy",
            ["login.intro"] = "Sign in with this computer's Windows account to get started.",
            ["login.domainHint"] = "Company domain account, already verified when you signed in to Windows. Just click Sign in",
            ["login.localHint"] = "Local account on this computer. Enter the Windows password you use to sign in",
            ["login.password"] = "Windows password (leave empty if the account has none)",
            ["login.server"] = "Server: {0}",
            ["login.button"] = "Sign in",
            ["login.useManual"] = "Connect to a server manually",
            ["login.useLogin"] = "Back to signing in with Windows",
            ["login.wrongPassword"] = "Wrong password. Enter the Windows password you use to sign in (not your PIN).",
            ["login.verifyFailed"] = "Windows couldn't verify this account: {0}",
            ["error.webview"] = "Microsoft Edge WebView2 Runtime is missing. Ask IT to install it, then try again.",
            ["confirm.notify"] = "FlyknitBuddy needs your approval for an action",
            ["toast.appName"] = "FlyknitBuddy",
            ["toast.confirmTitle"] = "FlyknitBuddy needs your approval",
            ["toast.allow"] = "Allow",
            ["toast.reject"] = "Reject",
            ["toast.view"] = "View",
            ["toast.done"] = "Task completed",
            ["toast.paused"] = "Task paused",
            ["toast.failed"] = "Task failed",
            ["loading.title"] = "Starting FlyknitBuddy…",
            ["loading.subtitle"] = "Your workspace will open automatically when it's ready.",
            ["mcp.oauthDone"] = "Sign-in finished. You can close this page; FlyknitBuddy shows whether the connection succeeded.",
            ["mcp.oauthFailed"] = "Sign-in didn't finish. Go back to FlyknitBuddy and connect again.",
            ["sel.title"] = "Quick translate",
            ["sel.target"] = "Translate into",
            ["sel.pin"] = "Pin (stay open when clicking elsewhere)",
            ["sel.close"] = "Close (Esc)",
            ["sel.sourceHint"] = "Edit the text and press Enter to translate again",
            ["sel.copy"] = "Copy",
            ["sel.copied"] = "Copied",
            ["sel.continue"] = "Continue in main window",
            ["sel.empty"] = "Couldn't read the selected text. Type or paste it here and press Enter.",
            ["sel.working"] = "Translating…",
            ["sel.noResult"] = "No translation came back. Try another language.",
            ["sel.truncated"] = "The selection is long, so only the first {0} characters were translated. Use Translate mode for whole files.",
            ["sel.error.auth"] = "The server refused the request. This computer's authorization may have expired; contact IT.",
            ["sel.error.busy"] = "The model service is busy or today's usage limit is reached. Try again later.",
            ["sel.error.network"] = "Can't reach the server. Check the network.",
            ["sel.error.failed"] = "Translation failed: {0}",
            ["lang.zh-CN"] = "Chinese",
            ["lang.vi"] = "Vietnamese",
            ["lang.en"] = "English",
            ["lang.km"] = "Khmer",
            ["lang.th"] = "Thai",
            ["lang.id"] = "Indonesian",
            ["lang.ja"] = "Japanese",
            ["lang.ko"] = "Korean",
        },
    };

    public static string Language { get; set; } = "zh-CN";

    public static string T(string key) =>
        Table.TryGetValue(Language, out var lang) && lang.TryGetValue(key, out var value) ? value
        : Table["zh-CN"].TryGetValue(key, out var fallback) ? fallback
        : key;
}
